package modelos;
// Generated 30 ene. 2021 12:38:12 by Hibernate Tools 5.4.21.Final

/**
 * Totales generated by hbm2java
 */
public class Totales implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private TotalesId id;

	public Totales() {
	}

	public Totales(TotalesId id) {
		this.id = id;
	}

	public TotalesId getId() {
		return this.id;
	}

	public void setId(TotalesId id) {
		this.id = id;
	}

}
