package modelos;
// Generated 30 ene. 2021 12:38:12 by Hibernate Tools 5.4.21.Final

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String nombre;
	private String clave;

	public Usuarios() {
	}

	public Usuarios(String nombre) {
		this.nombre = nombre;
	}

	public Usuarios(String nombre, String clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

}
